server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411/
